# Generated by Django 2.1.2 on 2018-12-12 13:40

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import sms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0014_auto_20181209_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن پیامک')),
                ('phone', models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/chavoshipour/sites/chatrbaazan/chatrbaazan'), upload_to=sms.models.generate_filename_phone, verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='sms_category', to='shop.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'سرویس اشتراک پیامک',
                'verbose_name_plural': 'سرویس اشتراک پیامک',
            ***REMOVED***,
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'موفق'), (2, 'نا موفق'), (3, 'در حال ارسال')], default=3, verbose_name='وضعیت')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smslog_sms', to='sms.Sms', verbose_name='sms')),
            ],
            options={
                'verbose_name': 'گزارش دهی سرویس پیامک',
                'verbose_name_plural': 'گزارش دهی سرویس پیامک',
            ***REMOVED***,
        ),
        migrations.CreateModel(
            name='SmsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره همراه')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'فعال'), (2, 'غیرفعال')], default=2, verbose_name='وضعیت')),
                ('code_verify', models.CharField(max_length=350, verbose_name='کدتایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_at', models.DateTimeField(verbose_name='زمان تایید شده')),
                ('send_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال کد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='کاربر', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اشتراک پیامک کاربر',
                'verbose_name_plural': 'اشتراک پیامک کاربر',
            ***REMOVED***,
        ),
        migrations.AddField(
            model_name='smslog',
            name='sms_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smsmlog_smsuser', to='sms.SmsUser'),
        ),
    ]
