# Generated by Django 2.1.2 on 2018-12-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsuser',
            name='active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید شده'),
        ),
    ]
