# Generated by Django 2.1.2 on 2019-01-10 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20181212_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='mobile',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='sms_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smsmlog_smsuser', to='sms.SmsUser'),
        ),
    ]
