# Generated by Django 2.1.2 on 2019-01-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20190110_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='phone',
        ),
        migrations.AddField(
            model_name='sms',
            name='sms_user',
            field=models.ManyToManyField(related_name='sms_smsUser', to='sms.SmsUser'),
        ),
    ]
