# Generated by Django 2.1.2 on 2019-01-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20190111_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='sms_user',
            field=models.ManyToManyField(related_name='sms_smsUser', to='sms.SmsUser', verbose_name='کاربران عضو اشتراک'),
        ),
    ]
