# Generated by Django 2.1.2 on 2018-11-30 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='مبلغ')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='مبلغ')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'در حال انجام'), (3, 'موفق'), (4, 'لغو شده توسط کاربر'), (5, 'مشکل در درگاه پرداخت')], default=1, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='مبلغ')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='مبلغ')),
                ('count', models.IntegerField(default=1, verbose_name='تعداد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartItem_cart', to='carts.Cart', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartItem_product', to='shop.Product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='CartSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=150, verbose_name='Ip')),
                ('key', models.CharField(max_length=500, verbose_name='Key Session')),
                ('header', models.TextField(verbose_name='Header Request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_session', to='carts.CartSession', verbose_name='جلسه'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
