# Generated by Django 2.1.2 on 2018-12-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session',
        ),
        migrations.DeleteModel(
            name='CartSession',
        ),
    ]
