# Generated by Django 2.1.2 on 2018-11-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=350, null=True, verbose_name='فامیلی')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=13, null=True, verbose_name='همراه')),
                ('email', models.CharField(max_length=50, verbose_name='ایمیل')),
                ('contact', models.TextField(verbose_name='متن')),
            ],
        ),
    ]
