# Generated by Django 2.1.2 on 2018-12-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'***REMOVED***,
        ),
    ]
