# Generated by Django 2.1.2 on 2018-12-05 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSendCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300, verbose_name='کد تخفیف')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضاء')),
                ('chatrbazi', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='مقدار چتر بازی')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'تایید شده'), (2, 'در انتظار تایید'), (3, 'لغو شده')], default=2, verbose_name='وضعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_send_code_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
