# Generated by Django 2.1.2 on 2018-12-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailemm',
            options={'verbose_name': 'ایمیل مارکتینگ', 'verbose_name_plural': 'ایمیل مارکتینگ'***REMOVED***,
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'verbose_name': 'ایمیل های داخل صف', 'verbose_name_plural': 'ایمیل های داخل صف'***REMOVED***,
        ),
        migrations.AddField(
            model_name='emailemm',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='عنوان ایمیل'),
        ),
    ]
