# Generated by Django 2.1.2 on 2018-12-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emm', '0003_auto_20181209_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
