# Generated by Django 2.1.2 on 2018-12-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emm', '0005_emailemm_email_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='email_address',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='آدرس ایمیل'),
        ),
    ]
