# Generated by Django 2.1.2 on 2018-12-29 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emm', '0006_emaillog_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailLog_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
