# Generated by Django 2.1.2 on 2018-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emm', '0007_auto_20181229_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='title_email',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='عنوان ایمیل'),
        ),
    ]
