# Generated by Django 2.1.2 on 2018-11-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_banner_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'بنر', 'verbose_name_plural': 'بنر'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'بنر', 'verbose_name_plural': 'بنر'},
        ),
    ]
