# Generated by Django 2.1.2 on 2018-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181126_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='available',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
