# Generated by Django 2.1.2 on 2018-11-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_banner_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_city', to='shop.City', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_company', to='shop.Company', verbose_name='کمپانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_label', to='shop.ProductLabel', verbose_name='تگ'),
        ),
    ]
