# Generated by Django 2.1.2 on 2018-11-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181128_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(max_length=500, verbose_name='کد تخفیف')),
                ('available', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کدتخفیف',
                'verbose_name_plural': 'کد تخفیف',
            ***REMOVED***,
        ),
        migrations.AddField(
            model_name='product',
            name='chatrbazi',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='مقدار چتر بازی'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Discount', verbose_name='کد تخفیف'),
        ),
    ]
