# Generated by Django 2.1.2 on 2018-12-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20181204_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gallery',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_gallery', to='shop.ProductGallery', verbose_name='گالری'),
        ),
    ]
