# Generated by Django 2.1.2 on 2018-12-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20181204_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='آدرس'),
        ),
    ]
