# Generated by Django 2.1.2 on 2018-12-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20181209_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproduct',
            options={'verbose_name': 'محصولات خریداری شده', 'verbose_name_plural': 'محصولات خریداری شده'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_code',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='کد تخفیف'),
        ),
    ]
