# Generated by Django 2.1.2 on 2018-12-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20181220_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chatrbazi',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مقدار چتر بازی'),
        ),
    ]
