# Generated by Django 2.1.2 on 2018-12-21 06:58

import django.core.files.storage
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20181220_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/chavoshipour/sites/chatrbaazan/chatrbaazan'), upload_to=shop.models.generate_filename_company, verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='company',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'فعال'), (3, 'غیرفعال'), (4, 'سطح پایین'), (5, 'سطح معمولی'), (6, 'سطح بالا'), (7, 'سطح فوق بالا')], default=4, verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='product',
            name='click',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد لایک'),
        ),
        migrations.AddField(
            model_name='product',
            name='failure',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد گزارش خرابی'),
        ),
    ]
