# Generated by Django 2.1.2 on 2018-12-21 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_failure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='failure_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
