# Generated by Django 2.1.2 on 2018-12-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_banner_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='location',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Top'), (2, 'Middle'), (1, 'Down'), (0, 'None')], default=3, null=True),
        ),
    ]
