# Generated by Django 2.1.2 on 2018-12-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20181222_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=350, null=True),
        ),
    ]
