# Generated by Django 2.1.2 on 2018-12-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'شرکت', 'verbose_name_plural': 'شرکت'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کد تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'گالری', 'verbose_name_plural': 'گالری'},
        ),
        migrations.AlterModelOptions(
            name='productlabel',
            options={'verbose_name': 'تگ ها', 'verbose_name_plural': 'تگ ها'},
        ),
    ]
