# Generated by Django 2.1.2 on 2018-12-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20181223_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهر'***REMOVED***,
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=350, null=True, verbose_name='لینک'),
        ),
    ]
