# Generated by Django 2.1.2 on 2018-12-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20181223_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='لینک'),
        ),
    ]
