# Generated by Django 2.1.2 on 2018-12-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_company_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, default='#', max_length=350, verbose_name='اینستاگرام')),
                ('telegram', models.CharField(blank=True, default='#', max_length=350, verbose_name='تلگرام')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='تلفن')),
                ('email', models.CharField(blank=True, max_length=350, null=True, verbose_name='ایمیل')),
                ('map_x', models.CharField(blank=True, max_length=100, null=True, verbose_name='نقطه ی y در نقشه')),
                ('enable', models.BooleanField(default=False, verbose_name='فعال')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس فروشگاه')),
            ],
            options={
                'verbose_name': 'تنظمیات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه',
            },
        ),
    ]
