# Generated by Django 2.1.2 on 2018-12-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_shopsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsetting',
            name='map_y',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نقطه ی y در نقشه'),
        ),
        migrations.AlterField(
            model_name='shopsetting',
            name='map_x',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نقطه ی x در نقشه'),
        ),
    ]
