# Generated by Django 2.1.2 on 2018-12-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20181224_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت'},
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
    ]
