# Generated by Django 2.1.2 on 2019-01-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20181228_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضاء'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='location',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Top'), (2, 'Middle'), (0, 'None')], default=3, null=True),
        ),
    ]
