# Generated by Django 2.1.2 on 2019-01-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20190101_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='ترتیب'),
        ),
    ]
