# Generated by Django 2.1.2 on 2018-12-05 07:24

import about.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'فعال'), (2, 'غیرفعال')], default=2, verbose_name='وضعیت')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/chavoshipour/sites/chatrbaazan/chatrbaazan'), upload_to=about.models.generate_filename_ProductPic, verbose_name='تصویر')),
            ],
        ),
    ]
