# Generated by Django 2.1.2 on 2018-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='disslike',
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Like'), (2, 'DissLike')], default=1, verbose_name='لایک'),
        ),
    ]
